name: Cron (testnet-sepolia)
on:
  workflow_dispatch:
  schedule:
    - cron: '15 0 * * 0'
jobs:
  dump-testnet-sepolia:
    uses: ./.github/workflows/dump.yml
    with:
      network: testnet-sepolia
