name: Network Data Dump (testnet-sepolia)
on:
  workflow_dispatch:
  schedule:
    - cron: '15 0 * * 3'
jobs:
  dump-testnet-sepolia:
    uses: ./.github/workflows/dump.yml
    with:
      network: testnet-sepolia
    secrets:
      RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}
