name: Dump contract data

on:
  workflow_dispatch:
  schedule:
    - cron: '10 0 * * 0'

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Get staging status
        id: status
        run: |
          json="$(npx ts-node ./src/status.ts --network staging)"
          echo $json
          echo "block1=$(echo $json | jq .epochFinishedBlock-1)" >> $GITHUB_OUTPUT
          echo "block2=$(echo $json | jq .epochAdvancedBlock)" >> $GITHUB_OUTPUT

      - name: Dump staging at epoch finished block
        id: dump1
        run: |
          npx ts-node ./src/dump.ts --network staging --block ${{ steps.status.outputs.block1 }}

      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          branch: "dump-staging-finished-${{ steps.status.outputs.block1 }}"
          title: "Dump staging at epoch finished block ${{ steps.status.outputs.block1 }}"
          commit-message: "Dump staging at epoch finished block ${{ steps.status.outputs.block1 }}"
          delete-branch: true

      - uses: peter-evans/enable-pull-request-automerge@v2
        with:
          pull-request-number: ${{ github.event.pull_request.number }}

      - name: Dump staging at epoch advanced block
        id: dump2
        run: |
          npx ts-node ./src/dump.ts --network staging --block ${{ steps.status.outputs.block2 }}

      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          branch: "dump-staging-advanced-${{ steps.status.outputs.block2 }}"
          title: "Dump staging at epoch advanced block ${{ steps.status.outputs.block2 }}"
          commit-message: "Dump staging at epoch advanced block ${{ steps.status.outputs.block2 }}"
          delete-branch: true

      - uses: peter-evans/enable-pull-request-automerge@v2
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
